apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::452706865406:role/eksctl-kCluster-nodegroup-web-ser-NodeInstanceRole-1GEWCWLQ4GHJ3
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::452706865406:role/eksctl-kCluster-nodegroup-web-ser-NodeInstanceRole-1GEWCWLQ4GHJ3\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::452706865406:user/rbac-user\n  username: rbac-user\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2021-04-04T14:00:22Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:mapRoles":{}}},"manager":"eksctl","operation":"Update","time":"2021-04-04T14:34:29Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{"f:mapUsers":{}},"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2021-04-04T19:09:24Z"}],"name":"aws-auth","namespace":"kube-system","resourceVersion":"51020","selfLink":"/api/v1/namespaces/kube-system/configmaps/aws-auth","uid":"d3a93594-060a-4ba2-8c60-4df74a087402"}}
  creationTimestamp: "2021-04-04T14:00:22Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: eksctl
    operation: Update
    time: "2021-04-04T14:34:29Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapUsers: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-04-04T19:23:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "53206"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d3a93594-060a-4ba2-8c60-4df74a087402
